[Simulation]
lMin = 2000
lMax = 70000
delta_t = 1
beta = 1e-5
exclude = False
total_time = 120
# NEW – mechanistic parameters
t_switch = 12
lambda_init= 1e-6
lambda_exp= 8e-4
Theta_init=2000
Theta_exp=2000

