[Simulation]
lMin = 250
lMax = 1500
delta_t = 1
beta = 1e-5
exclude = False
total_time = 480
# NEW – mechanistic parameters
t_switch = 30
lambda_init= 8e-5
lambda_exp= 3e-4
Theta_init=2000
Theta_exp=2000