import argparse
import os
import sys
import pickle
from collections import defaultdict
import networkx as nx

# Ensure the script is run from the project root directory
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, os.pardir, os.pardir))
sys.path.insert(0, project_root)

from SinglCellSim.Coal.coalSim import coalescent_tree_simulation, collect_leaf_nodes


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a coalescence tree with mutations.")
    parser.add_argument("--SNV-rate", type=float, required=True, help="Mutation rate per base per generation.")
    parser.add_argument("--num-cells", type=int, required=True, help="Number of cells.")
    parser.add_argument("--genome-len", type=str, required=True, help="Length of the genome (e.g., '100kb', '1mb').")
    parser.add_argument("--eff-pop-size", "-N", type=int, default=100, help="Effective population size for the coalescence.")
    parser.add_argument("--output", type=str, required=True, help="Output file to save the tree and mutations.")
    
    args = parser.parse_args()

    # Parse genome length
    if args.genome_len.endswith("kb"):
        genome_length = int(float(args.genome_len[:-2]) * 1000)
    elif args.genome_len.endswith("mb"):
        genome_length = int(float(args.genome_len[:-2]) * 1e6)
    else:
        genome_length = int(args.genome_len)

    # Generate the coalescence tree (and output to a .pkl file)
    output_tree_filename = args.output.replace(".pkl", "_tree.pkl")
    output_visualization_filename = args.output.replace(".pkl", "_tree.png")
    
    coalescent_tree_simulation(
        args.num_cells,
        N=args.eff_pop_size,
        genome_length=genome_length,
        mutation_rate=args.SNV_rate,
        filename=output_tree_filename
    )
    
    # Load the .pkl file generated by coalescent_tree_simulation
    with open(output_tree_filename, "rb") as f:
        output_tree = pickle.load(f)

    tree = output_tree["topology"]
    branch_lengths = output_tree["branch_lengths"]
    mutations = output_tree["mutations"]

    # Collect all leaf nodes
    leaf_nodes = []
    collect_leaf_nodes(tree, list(tree.nodes())[0], leaf_nodes)  # Start from the root (node 0)

    # Count the occurrences of each mutation in leaf nodes only
    leaf_mutation_counts = defaultdict(int)
    for leaf in leaf_nodes:
        for mutation in mutations.get((tree.predecessors(leaf), leaf), []):
            leaf_mutation_counts[mutation] += 1
    
    # Calculate VAFs based on leaf nodes only
    vaf_info = {mutation: count / len(leaf_nodes) for mutation, count in leaf_mutation_counts.items()}

    # Save the tree, mutations, VAFs, and node mutations to the output file
    output_data = {
        "tree": tree,
        "mutations": mutations,
        "vaf_info": vaf_info,
        "node_mutations": mutations  # Assuming node mutations are in the 'mutations' dict
    }

    with open(args.output, "wb") as f:
        pickle.dump(output_data, f)

    print(f"Coalescence tree, mutations, VAFs, and node mutations saved to '{args.output}'.")
